#include "main.h"

#ifndef SSD1306_DEFINES_H_
#define SSD1306_DEFINES_H_

#define USE_DMA
#define SSD1306_I2C_PORT		hi2c1 	    // I2C port as defined in main generated by CubeMx
#define SSD1306_I2C_ADDR	    (0x3C<<1)	// I2C address display
#define SSD1306_128X64 				        // OR #define SSD1306_128X32
#endif
